### ISSUE TITLE
Using DruidTools in dor-services

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/dor-services#155]
What is the general policy on using DruidTools in dor-services? During recent discussions about this in slack, @atz noted that dor-services must be allowed to work with things that are not a valid DRUID.

Is this the desired or necessary behavior?  Otherwise, dor-services could apply a global rule that everything dor-services handles must be a valid DRUID, so that DruidTools could be used consistently for parsing and managing DRUIDs for methods like `item.pid` or `item.id`.

**Comment by LynnMcRae** [comment]
This is possibly a situation that might only arise in Argo, where seeing objects with non-druid PIDs is needed administratively.  See current argo-stage and look at the Empty Fields facets for "No object type".   We have 290,000 non-conformant objects from some experimental loading of Fedora objects, with PIDs like changeme:3 and other, longer values including UUIDs.

**Comment by LynnMcRae** [comment]
You can see these objects but with a warning about a bad druid

**Comment by darrenleeweber** [comment]
For reference, the slack chat was around creating this method in Argo:
https://github.com/sul-dlss/argo/blob/issues76-apo-access/app/controllers/application_controller.rb#L68-L93

Where it seems that most everything should be a DRUID, but we need to allow for things that are not.  The code does check for a valid DRUID and simply issues are warning when it's not and allows Dor to find it (dor-services).  The warning may help detect and correct typos.

**Comment by jmartin-sul** [comment]
my $0.02:

i think that it'd be nice for dor-services to provide tools and convenience methods that would verify things like PID format (or *maybe* modes on existing functionality, but i'd prefer helper and wrapper methods around the existing stuff).  but as a very general purpose tool consumed by many disparate downstream codebases, it should be allowed to work with bad data, and should not enforce all of the data sanitization it might provide, or that other applications might want.  it seems to me that it'd be better to write those sorts of safe data manipulation tools on top of dor-services, and to have client apps use those tools instead of dor-services.

at the end of the day, there has to be some final layer that performs unchecked/unsafe actions as part of implementing higher level safer actions, and dor-services is already that, so it makes more sense to me to continue using it as such and to build other things on top for more constrained work.

**Comment by LynnMcRae** [comment]
There are certainly processes that know it's a druid and has to be a druid --- creating a valid DOR object for instance (I think the crud in DOR test got there via Fedora APIs, not via DOR services, at least I hope so). But reading objects ... take what comes? give a warning (which one can ignore as appropriate)? take a PID as an opaque string and assume the reference will succeed or fail based on what's actually in DOR and that's all that matters? Historical note, it wasn't until after the early DOR + SALT two-Fedora environment that we decided to stick with druids for all, not a multi namespace regime over multiple repositories.

**Comment by drh-stanford** [comment]
My thoughts on this (and the related issue in https://github.com/sul-dlss/argo/issues/567) is that we will eventually need a refactoring such that `Druid` is a class, akin to `DruidTools::Druid`, that provides some basic services that can be used to build off of. We might have a `DruidTree` class for example that uses `Druid` -- to avoid the problem in DruidTools where the uuid class is tied to other storage related things and whatnot.

I think this is a good example of our primitive obsession code smell in that `druid` is always a `String` whereever we use it -- and it's used everywhere (shotgun surgery?).  So, below is a strawman for what basic services a `Druid` class might contain (lifted from DruidTools) and how it would be used in various Repositories:

  https://gist.github.com/drh-stanford/23ad4a1abdd9801d5b78

I'm not a big fan of DruidTools because that class is tied to some storage related stuff and whatnot, and I also think Druid is better off as a top-level global class name. If we needed other prefixes, we could have a Uuid superclass for Druid for things that are not druids but used as identifers nonetheless.

**Comment by darrenleeweber** [comment]
:+1: for the extraction example ^^

**Comment by atz** [comment]
We do use `DruidTools` in 26 places throughout `lib`, currently.  I agree w/ DRH that we are sorta dumb and repetitive about creating DruidTools objects.  I think this discussion was clarifying, but doesn't drive towards any actionable implementation, so I'm closing the ticket.
