### ISSUE TITLE
Provide top level API to load from Fedora, without Solr

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/dor-services#177]
The current top level abstraction, the `Dor.find` method is a combination of Solr and Fedora data.  Provide a complementary top level public method, e.g. `Dor.load` that can take relevant arguments, like the model type required or a set of model types that are acceptable.  This should be able to accept a `Dor::Item` or any array of model types (`[Dor::Item, Dor::Collection, Dor::Set]`) and return only a model type that has any intersection with those types required.  It should not coerce (type cast) a native model into a non-native type, raising an exception if a PID is found of a type that has no intersection with the required types.  (This method should not use any Solr data, it should focus solely on Fedora.)

**Comment by jmartin-sul** [comment]
FWIW...

the basic version of this (load from fedora w/o involving solr) actually seems to exist already, in the form of `Dor.load_instance`.  that method is in use by at least `Dor::IndexingService` (which can't assume that the object is already properly indexed, since it was originally written to deal with unindexed and incorrectly indexed objects).

https://github.com/sul-dlss/dor-services/blob/v5.13.0/lib/dor-services.rb#L17-L28
https://github.com/sul-dlss/dor-services/blob/v5.13.0/lib/dor/services/indexing_service.rb#L58

it doesn't do the thing described above where a list of acceptable types for the return object is provided, but it does at least determine object type by looking at `identityMetadata`, which @LynnMcRae said should be the authoritative determinant of object type (in a conversation on slack this afternoon).

**Comment by cbeer** [comment]
Fixed by #248.
